---
title: "Cost of Living Estimates"
subtitle: "Examples for census tracts in the National Capital Region."
---

<br>
<br>

## Average Housing Cost per month

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(tigris)
library(dplyr)
library(stars)
```


```{r, echo=FALSE, warning=FALSE, include=FALSE}
#data
county_fairfax <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/fairfax_fallschurch_fairfaxcity_2022_food_insecurity_rev.csv") %>% select(-c(moe, PUMA5CE_20))
county_arl <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/arlington_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_alexandria <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/alexandria_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_prince_will <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/princewilliam_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_loudoun <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/loudoun_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_frederick <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/12.frederick_md_2022_food_insecurity_rev.csv") %>% select(-c(X, moe.x, moe.y, PUMA20))
county_montgomery <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/montgomery_md_2022_food_insecurity_rev.csv") %>% select(-c(PUMA20, moe))
county_princegeorge <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/princegeorge_2022_food_insecurity_rev.csv") %>% select(-c(X, PUMA20, moe))
county_wash_dc <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/dc_2022_food_insecurity_rev.csv") %>% select(-c(X,  PUMA20, PUMA5CE_new, other_cost_20))
county_charles <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/charles_md_2022_food_insecurity_rev.csv") %>% select(-c(X, PUMA20, other_cost_20, moe))
#county_fallsch <- read.csv("~/Documents/R/git/cost-living-website/code/web/data_estimation/") %>% select(-c(X, PUMA20, other_cost_20, moe))


#join data
county <- rbind(county_fairfax, county_arl, county_alexandria, county_prince_will, county_loudoun, county_frederick, county_montgomery, county_princegeorge, county_wash_dc, county_charles)

#data
county_tract_sum <- county %>% group_by(GEOID=geoid) %>% summarise(housing_cost_avr = weighted.mean(housing_cost, num_hh, na.rm = TRUE), 
                                                                   food_cost_avr = weighted.mean(food_costs, num_hh, na.rm = TRUE), 
                                                                   trans_cost_avr = weighted.mean(trans_cost, num_hh, na.rm = TRUE),
                                                                   internet_cost_avr = weighted.mean(internet_cost, num_hh, na.rm = TRUE),
                                                                   healthcare_cost_avr = weighted.mean(healthcare_cost, num_hh, na.rm = TRUE),
                                                                   cc_cost_avr = weighted.mean(cc_cost, num_hh, na.rm = TRUE)
                                                                   )
#tracts geometry
tracts_county_va <- tracts(state = "VA", county = c("Fairfax County", "Arlington County", "Alexandria City", "Prince William County", "Loudoun County", 
                                                    "Falls Church City", "Fairfax City", "Manassas City", "Manassas Park City"), cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county_md <- tracts(state = "MD", county = c("Frederick County", "Montgomery County", "Prince George's County", "Charles County"), cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county_dc <- tracts(state = "DC", cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county <- rbind(tracts_county_va, tracts_county_md, tracts_county_dc)

#data plot
tracts_county$GEOID <- as.character(tracts_county$GEOID)
county_tract_sum$GEOID <- as.character(county_tract_sum$GEOID)
data_plot <- tracts_county %>% left_join(county_tract_sum, by = "GEOID" ) 

#counties geometry
shape_counties <- tigris::counties(state = c("VA", "MD", "DC"), class = "sf")
shape_counties_dmv <- shape_counties %>% filter(GEOID == 51013 | GEOID ==51059 | GEOID == 51600 | GEOID == 51107 | GEOID == 51610 | GEOID == 51683 | 
                                                  GEOID == 51685 | GEOID == 51153 | GEOID == 51510 | GEOID == 11001 | GEOID ==  24021 | GEOID == 24031 | GEOID == 24033 | GEOID == 24017
                                                ) 
#format for counties
shape_counties_dmv <- st_transform(shape_counties_dmv, 4326 )

```

```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height= 10}
library(sf)
library(leaflet)
library(dplyr)
library(readr)



#format st
data_plot_sf <- st_as_sf(data_plot) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", data_plot_sf$housing_cost_avr, bins = 10)

# map
map_housing <- leaflet(data_plot_sf , options = leafletOptions(attributionControl = FALSE)) %>%
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("Average Cost of Housing", "topright") %>%
  addLegend("bottomright", pal, data_plot_sf$housing_cost_avr, opacity = .7) %>%
  addPolygons(
    fillColor = pal(data_plot_sf$housing_cost_avr), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Average Cost of Housing: $", round(data_plot_sf$housing_cost_avr,0) ,  "<br/>", 
      "Census tract: ", data_plot_sf$NAMELSAD, "<br/>"
      #"Proportion HH Food Insecurity ", round(data_plot_sf$housing_cost_avr,2), "<br/>",
      #"PUMA: ", food_sec_tract_num_plot$pumas
    ) %>% 
      lapply(htmltools::HTML) 
  ) %>%
  addPolylines(data = shape_counties_dmv, color = "black", opacity = 1, weight = 2.5) 

map_housing
```


<br>
<br>

## Average Food Cost per month

```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height= 10}
library(sf)
library(leaflet)
library(dplyr)
library(readr)

#format st
data_plot_sf <- st_as_sf(data_plot) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", data_plot_sf$food_cost_avr, bins = 10)

# map
map_food <- leaflet(data_plot_sf , options = leafletOptions(attributionControl = FALSE)) %>%
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("Average Cost of Food", "topright") %>%
  addLegend("bottomright", pal, data_plot_sf$food_cost_avr, opacity = .7) %>%
  addPolygons(
    fillColor = pal(data_plot_sf$food_cost_avr), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Average Cost of Food: $", round(data_plot_sf$food_cost_avr,0) ,  "<br/>", 
      "Census tract: ", data_plot_sf$NAMELSAD, "<br/>"
      #"Proportion HH Food Insecurity ", round(data_plot_sf$food_cost_avr,2), "<br/>",
      #"PUMA: ", food_sec_tract_num_plot$pumas
    ) %>% 
      lapply(htmltools::HTML) 
  ) %>%
  addPolylines(data = shape_counties_dmv, color = "black", opacity = 1, weight = 2.5) 

map_food
```

<br>
<br>

## Average Internet Cost per month

```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height= 10}
library(sf)
library(leaflet)
library(dplyr)
library(readr)

#format st
data_plot_sf <- st_as_sf(data_plot) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", data_plot_sf$internet_cost_avr, bins = 10)

# map
map_internet <- leaflet(data_plot_sf , options = leafletOptions(attributionControl = FALSE)) %>%
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("Average Cost of Food", "topright") %>%
  addLegend("bottomright", pal, data_plot_sf$internet_cost_avr, opacity = .7) %>%
  addPolygons(
    fillColor = pal(data_plot_sf$internet_cost_avr), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Average Cost of Food: $", round(data_plot_sf$internet_cost_avr,0) ,  "<br/>", 
      "Census tract: ", data_plot_sf$NAMELSAD, "<br/>"
      #"Proportion HH Food Insecurity ", round(data_plot_sf$internet_cost_avr,2), "<br/>",
      #"PUMA: ", food_sec_tract_num_plot$pumas
    ) %>% 
      lapply(htmltools::HTML) 
  ) %>%
  addPolylines(data = shape_counties_dmv, color = "black", opacity = 1, weight = 2.5) 

map_internet
```

<br>
<br>

## Average Transportation Cost per month

```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height= 10}
library(sf)
library(leaflet)
library(dplyr)
library(readr)

#format st
data_plot_sf <- st_as_sf(data_plot) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", data_plot_sf$trans_cost_avr, bins = 10)

# map
map_trasportation <- leaflet(data_plot_sf , options = leafletOptions(attributionControl = FALSE)) %>%
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("Average Cost of Food", "topright") %>%
  addLegend("bottomright", pal, data_plot_sf$trans_cost_avr, opacity = .7) %>%
  addPolygons(
    fillColor = pal(data_plot_sf$trans_cost_avr), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Average Cost of Food: $", round(data_plot_sf$trans_cost_avr,0) ,  "<br/>", 
      "Census tract: ", data_plot_sf$NAMELSAD, "<br/>"
      #"Proportion HH Food Insecurity ", round(data_plot_sf$trans_cost_avr,2), "<br/>",
      #"PUMA: ", food_sec_tract_num_plot$pumas
    ) %>% 
      lapply(htmltools::HTML) 
  ) %>%
  addPolylines(data = shape_counties_dmv, color = "black", opacity = 1, weight = 2.5) 

map_trasportation
```

<br>
<br>

## Average Childcare Cost per month

```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height= 10}
library(sf)
library(leaflet)
library(dplyr)
library(readr)

#format st
data_plot_sf <- st_as_sf(data_plot) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", data_plot_sf$cc_cost_avr, bins = 10)

# map
map_trasportation <- leaflet(data_plot_sf , options = leafletOptions(attributionControl = FALSE)) %>%
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("Average Cost of Food", "topright") %>%
  addLegend("bottomright", pal, data_plot_sf$cc_cost_avr, opacity = .7) %>%
  addPolygons(
    fillColor = pal(data_plot_sf$cc_cost_avr), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Average Cost of Food: $", round(data_plot_sf$cc_cost_avr,0) ,  "<br/>", 
      "Census tract: ", data_plot_sf$NAMELSAD, "<br/>"
      #"Proportion HH Food Insecurity ", round(data_plot_sf$cc_cost_avr,2), "<br/>",
      #"PUMA: ", food_sec_tract_num_plot$pumas
    ) %>% 
      lapply(htmltools::HTML) 
  ) %>%
  addPolylines(data = shape_counties_dmv, color = "black", opacity = 1, weight = 2.5) 

map_trasportation
```

