---
title: "Untitled"
author: "Kishore"
date: "4/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(tigris)
library(dplyr)
library(stars)
```


```{r, echo=FALSE, warning=FALSE, include=FALSE}

data <- read.csv("~/git/cost-living/code/food_insecurity/2.results_snap_snap_max/results/ncr_combined_2022_SNAP_by_tract.csv")


# #tracts geometry
tracts_county_va <- tracts(state = "VA", county = c("Fairfax County", "Arlington County", "Alexandria City", "Prince William County", "Loudoun County", 
                                                    "Falls Church City", "Fairfax City", "Manassas City", "Manassas Park City"), cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county_md <- tracts(state = "MD", county = c("Frederick County", "Montgomery County", "Prince George's County", "Charles County"), cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county_dc <- tracts(state = "DC", cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county <- rbind(tracts_county_va, tracts_county_md, tracts_county_dc)

tracts_county$GEOID <- as.character(tracts_county$GEOID)
data$geoid <- as.character(data$geoid)


colnames(data)[1] <- "GEOID"

data_plot <- left_join(tracts_county, data, by = "GEOID")

#counties geometry
shape_counties <- tigris::counties(state = c("VA", "MD", "DC"), class = "sf")
shape_counties_dmv <- shape_counties %>% filter(GEOID == 51013 | GEOID ==51059 | GEOID == 51600 | GEOID == 51107 | GEOID == 51610 | GEOID == 51683 | 
                                                  GEOID == 51685 | GEOID == 51153 | GEOID == 51510 | GEOID == 11001 | GEOID ==  24021 | GEOID == 24031 | GEOID == 24033 | GEOID == 24017
                                                ) 
#format for counties
shape_counties_dmv <- st_transform(shape_counties_dmv, 4326 )

```





```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height= 10}
library(sf)
library(leaflet)
library(dplyr)
library(readr)


#format st
data_plot_sf <- st_as_sf(data_plot) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", data_plot_sf$households_represented, bins = 10)

# map
map_snap_hh <- leaflet(data_plot_sf , options = leafletOptions(attributionControl = FALSE)) %>%
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("NUMBER OF HOUSEHOLDS RECEIVING SNAP BY COUNTY", "topright") %>%
  addLegend("bottomright", pal, data_plot_sf$households_represented, opacity = .7) %>%
  addPolygons(
    fillColor = pal(data_plot_sf$households_represented), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Number of Snap households:", data_plot_sf$households_represented ,  "<br/>", 
      "Census tract: ", data_plot_sf$NAMELSAD, "<br/>",
      "Monthly mean income: ", round(data_plot_sf$monthly_mean_income, 1), "<br/>",
      "Monthly mean snap benefit: ", round(data_plot_sf$monthly_mean_SNAP_benefit,1), "<br/>"
    ) %>% 
      lapply(htmltools::HTML) 
  ) %>%
  addPolylines(data = shape_counties_dmv, color = "black", opacity = 1, weight = 2.5) 

map_snap_hh

```











```{r, echo=FALSE, warning=FALSE, include=FALSE}

#data
county_fairfax <- read.csv("~/git/cost-living-website/docs/data_estimation/fairfax_fallschurch_fairfaxcity_2022_food_insecurity_rev.csv") %>% select(-c(moe, PUMA5CE_20))
county_arl <- read.csv("~/git/cost-living-website/docs/data_estimation/arlington_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_alexandria <- read.csv("~/git/cost-living-website/docs/data_estimation/alexandria_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_prince_will <- read.csv("~/git/cost-living-website/docs/data_estimation/princewilliam_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_loudoun <- read.csv("~/git/cost-living-website/docs/data_estimation/loudoun_2022_food_insecurity_rev.csv") %>% select(-c(X, moe, PUMA5CE_20))
county_frederick <- read.csv("~/git/cost-living-website/docs/data_estimation/12.frederick_md_2022_food_insecurity_rev.csv") %>% select(-c(X, moe.x, moe.y, PUMA20))
county_montgomery <- read.csv("~/git/cost-living-website/docs/data_estimation/montgomery_md_2022_food_insecurity_rev.csv") %>% select(-c(PUMA20, moe))
county_princegeorge <- read.csv("~/git/cost-living-website/docs/data_estimation/princegeorge_2022_food_insecurity_rev.csv") %>% select(-c(X, PUMA20, moe))
county_wash_dc <- read.csv("~/git/cost-living-website/docs/data_estimation/dc_2022_food_insecurity_rev.csv") %>% select(-c(X,  PUMA20, PUMA5CE_new, other_cost_20))
county_charles <- read.csv("~/git/cost-living-website/docs/data_estimation/charles_md_2022_food_insecurity_rev.csv") %>% select(-c(X, PUMA20, other_cost_20, moe))



#join data
county <- rbind(county_fairfax, county_arl, county_alexandria, county_prince_will, county_loudoun, county_frederick, county_montgomery, county_princegeorge, county_wash_dc, county_charles)


food_sec_tract_num_long <- county %>% group_by(geoid, food_insecure_status) %>% summarise(total_hh = sum(num_hh, na.rm = TRUE), puma=first(PUMA5CE))


food_sec_tract_num <- food_sec_tract_num_long %>% pivot_wider(names_from = food_insecure_status, values_from = total_hh) %>% 
  mutate(tot_hh= `At-Risk`+ `Food Insecure` + `Food Secure`,
         at_risk_pc= `At-Risk`/tot_hh,
         insecure_pc= `Food Insecure`/tot_hh,
         secure_pc= `Food Secure`/tot_hh,
         pumas = first(puma)
         )

# #tracts geometry
tracts_county_va <- tracts(state = "VA", county = c("Fairfax County", "Arlington County", "Alexandria City", "Prince William County", "Loudoun County", 
                                                    "Falls Church City", "Fairfax City", "Manassas City", "Manassas Park City"), cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county_md <- tracts(state = "MD", county = c("Frederick County", "Montgomery County", "Prince George's County", "Charles County"), cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county_dc <- tracts(state = "DC", cb = FALSE, year = 2020) %>% select(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD, geometry)

tracts_county <- rbind(tracts_county_va, tracts_county_md, tracts_county_dc)

#data plot
tracts_county$GEOID <- as.character(tracts_county$GEOID)
food_sec_tract_num$geoid <- as.character(food_sec_tract_num$geoid)
food_sec_tract_num <- rename(food_sec_tract_num, GEOID = geoid)
food_sec_tract_num <- select(food_sec_tract_num, -c("NA"))

data_plot <- left_join(tracts_county, food_sec_tract_num, by = "GEOID")

data_plot$geometry <- st_cast(data_plot$geometry,"MULTIPOLYGON")

data <- read.csv("~/git/cost-living/code/food_insecurity/2.results_snap_snap_max/results/ncr_combined_2022_SNAP_by_tract.csv")

colnames(data)[1] <- "GEOID"
merged_data <- merge(data, data_plot, by = "GEOID")
merged_data$geometry <- st_cast(merged_data$geometry,"MULTIPOLYGON")


```










```{r, echo=FALSE, warning=FALSE, fig.width = 11, fig.height= 7}


library(ggiraph)


# Create plot for proportion of households facing food insecurity with tooltips
plot_snap_finsec <- ggplot(merged_data, aes(households_represented, insecure_pc, fill = insecure_pc, tooltip = paste0("Census Tract: ", NAME, "<br>", "Food Insecurity: ", insecure_pc, "%","<br>", "Number of households: ", households_represented, "<br>"))) + 
  geom_point_interactive(color = "black", size = 2, shape = 20, aes(data_id = GEOID)) +
  scale_fill_viridis(option = "viridis", direction = 1) + 
  labs(title = 'Food Insecurity and Number of SNAP Households by Census Tracts in NCR Region', 
        x = "Number of SNAP Households", 
       y = "Proportion of Households Facing Food Insecurity") + 
  theme(legend.text = element_text(size = 14), 
        legend.position = "bottom") +
guides(fill = FALSE) 


# Create plot for choropleth map with tooltips
c <- ggplot(merged_data, aes(fill = insecure_pc, tooltip = paste0("Census Tract: ", NAME, "<br>", "Food Insecurity: ", insecure_pc, "%","<br>", "Number of households: ", households_represented, "<br>"), geometry = geometry )) +
  geom_sf_interactive(aes(data_id = GEOID)) + 
  scale_fill_viridis(option = "viridis", direction = 1) + 
  theme_void() + 
  guides(fill = guide_legend(title = "Food Insecurity %", title.position = "top", 
                             label.position = "bottom", label.theme = element_text(size = 8)))

# Combine plots using girafe
girafe(ggobj = plot_snap_finsec + c) %>%
  girafe_options(opts_hover(css = "fill:cyan;")) 



```









